import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
    header: { alignItems: 'center', marginBottom: 30 },
    subtitle: {
        fontSize: 16,
        color: 'rgba(255,255,255,0.8)',
        marginTop: 5,
    },
    mainCard: {
        backgroundColor: 'rgba(255,255,255,0.15)',
        borderRadius: 25,
        padding: 30,
        alignItems: 'center',
        marginBottom: 25,
    },
    activityIcon: {
        width: 80,
        height: 80,
        borderRadius: 40,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 15,
    },
    activityText: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#fff',
        marginBottom: 5,
    },
    timestamp: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.7)',
    },
    envRow: {
        flexDirection: 'row',
        marginBottom: 25,
        justifyContent: 'space-between',
    },
    envCard: {
        flex: 1,
        backgroundColor: 'rgba(255,255,255,0.1)',
        borderRadius: 15,
        padding: 15,
        alignItems: 'center',
        marginHorizontal: 5,
    },
    envLabel: {
        fontSize: 12,
        color: 'rgba(255,255,255,0.7)',
        marginTop: 5,
    },
    envValue: {
        fontSize: 14,
        fontWeight: '600',
        color: '#fff',
        marginTop: 2,
    },
    statsRow: {
        flexDirection: 'row',
        marginBottom: 30,
        justifyContent: 'space-between',
    },
    statCard: {
        flex: 1,
        backgroundColor: 'rgba(255,255,255,0.1)',
        borderRadius: 15,
        padding: 20,
        alignItems: 'center',
        marginHorizontal: 5,
    },
    statValue: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#fff',
    },
    statLabel: {
        fontSize: 12,
        color: 'rgba(255,255,255,0.7)',
        marginTop: 5,
    },
    ttsBtn: {
        backgroundColor: '#FF6B6B',
        width: 60,
        height: 60,
        borderRadius: 30,
        alignSelf: 'center',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#FF6B6B',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
        elevation: 8,
    },
});